# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Slot2API/Slot2API.csproj", "Slot2API/"]
COPY ["PRN232.ServiceDefaults/PRN232.ServiceDefaults.csproj", "PRN232.ServiceDefaults/"]
RUN dotnet restore "./Slot2API/Slot2API.csproj"
COPY . .
WORKDIR "/src/Slot2API"
RUN dotnet build "./Slot2API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
RUN dotnet publish "./Slot2API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Slot2API.dll"]