services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8000:8080"

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DemoOk;User ID=sa;Password=Shinjuuichi@11;TrustServerCertificate=True
    ports:
      - "8001:8080"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

      - ConnectionStrings__BaseUrl=http://apigateway:8080
    ports:
      - "8002:8080"
