services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - microservices-network

  webapi:
    image: ${DOCKER_REGISTRY-}web-api
    build:
      context: .
      dockerfile: Slot2API/Dockerfile
    networks:
      - microservices-network

  webmvc:
    image: ${DOCKER_REGISTRY-}web-mvc
    build:
      context: .
      dockerfile: WebMVC/Dockerfile
    networks:
     - microservices-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Okelabubu@123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - microservices-network

volumes:
    mssql_data:

networks:
    microservices-network:
        driver: bridge
