name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker build . --file ApiGateway/Dockerfile --tag api-gateway:$(date +%s)
           docker build . --file Slot2API/Dockerfile --tag web-api:$(date +%s)
           docker build . --file WebMVC/Dockerfile --tag web-mvc:$(date +%s)
      
      
      
